### PR TITLE
Added dal region

### PR DESCRIPTION
**Pull request by KeerthanaAP**
Mapped 'dal' zone to 'dal' region, according to the doc https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/book/src/reference/regions-zones-mapping.md

### CODE REVIEW

**Comment by mkumatag** [comment]
@KeerthanaAP please add more information in the description about the fix you are making.

/cc @bkhadars @dharaneeshvrd @Prajyot-Parab 

ptal

**Comment by dharaneeshvrd** [comment]
dal and dal12 is valid region and zone. Lgtm!

**Comment by Prajyot-Parab** [comment]
Inline with endpoint requirements.
/lgtm

**Review by mkumatag — APPROVED** [review]
/approve

**Pull request merged**
