### PR TITLE
PowerVS: Add an only IPI regions list

### PR DESCRIPTION
**Pull request by hamzy**
In order for the IPI installer to be able to use this module, it needs the ability to have the list of regions to only include supported regions.

### CODE REVIEW

**Comment by hamzy** [comment]
I looks like IPI will have to live with updating the same code in two different repos instead of using a module.

**Comment by mkumatag** [comment]
> I looks like IPI will have to live with updating the same code in two different repos instead of using a module.

I don't see any better way, @Karthik-K-N @dharaneeshvrd if you have any better idea for this?

**Comment by hamzy** [comment]
This PR does provide a way to solve the problem.  It also effects the code minimally without altering every API used.

**Comment by mkumatag** [comment]
> This PR does provide a way to solve the problem. It also effects the code minimally without altering every API used.

But I see repeated code there, need find a way to reduce that.

**Comment by hamzy** [comment]
Hrm, when you force push a new version, you cannot reopen the PR.  How weird.

**Pull request closed without merging**
